title: Cerddoriaeth Clasurol
email: rafik.harrington@glantaf.cymru
description: >- # this means to ignore newlines until "baseurl:"
  Gwefan am wrando a chwarae Cerddoriaeth Clasurol
github_username: skuzzymiglet
minimal_mistakes_skin: dark 
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rafik Harrington"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Disgybl Bl9 Glantaf"
  links:

footer:
  links:
    - label: "Cod"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/skuzzymiglet/gwefan-cerddoriaeth-clasurol/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
